TELEGRAM_BOT_TOKEN=7519466093:AAFsduq0HfhUrdLqYYudLCM-JqB9xvtBQ-g
OPENAI_API_KEY=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
